version: '3.3'

services:
  app:
    build: .
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlb
      PGDATA: /data/postgres
    volumes:
      - mlb:/data/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mlb:
