version: 2.1

orbs:
  wait-for: cobli/wait-for@0.0.2

jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:latest
        environment:
          POSTGRES_HOST: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mlb_test
    working_directory: ~/mlb-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install dependencies
          command: npm install
      - wait-for/sh-command:
          sh-command: |
            "[for i in `seq 1 10`;
              do
                nc -z db_test 5432 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting for Postgres && exit 1]"
          seconds_between_retries: 10
          timeout: 60
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fb:69:ec:50:71:0e:d7:c9:bf:33:15:41:6c:6b:32:13"
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
