version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/mlb-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f9:e8:59:5d:ee:de:02:ce:fc:5a:f7:54:8e:94:11:44"
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
