version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mlb_test
    working_directory: ~/mlb-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fb:69:ec:50:71:0e:d7:c9:bf:33:15:41:6c:6b:32:13"
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
