version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/mlb-api
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: docker-compose up -d --build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: docker-compose run app npm test
